# .streamlit/secrets.toml
[general]
GOOGLE_API_KEY = "AIzaSyCN6sMI7nRyuwgTovMrNbs2OdoOIEFAv60"

[database]
DB_NAME = "neondb"
DB_USER = "neondb_owner"
DB_PASSWORD = "npg_1IeuRlwZdc8a"
DB_HOST = "ep-dark-firefly-a8fjfreu-pooler.eastus2.azure.neon.tech"
DB_PORT = "5432"

[email]
SENDER_EMAIL = "uditrajsingh815@gmail.com"
SENDER_PASSWORD = "zpjb vgul dzkc jpbe"
